---
# Copyright 2024
#
# Everyone is permitted to copy, distribute, modify, merge, sell, publish,
# sublicense or whatever the fuck they want with this software but at their
# OWN RISK.
# The author has absolutely no fucking clue what the code in this project
# does. It might just fucking work or not, there is no third option.
#
# IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.
# ---
version: "3.8"

services:
  # ┌───────────────────────────────────────────────────────────────────────────────────┐
  # │ Homer: A very simple static homepage for your server.                             │
  # │                                                                                   │
  # │ Docs: https://github.com/bastienwirtz/homer/blob/main/README.md#table-of-contents │
  # └───────────────────────────────────────────────────────────────────────────────────┘
  home-dashboard:
    image: oci.chezmoi.sh/localhost/alpine/homer:stable
    cap_drop:
      - ALL
    networks:
      caddy-internal:
      default: # NOTE: Required for 3rd-party services to fetch API
    read_only: true
    restart: unless-stopped
    user: lighttpd

  # ┌───────────────────────────────────────────────────────────────────────────┐
  # │ Gatus: A simple, fast and scalable status page for your services and APIs.│
  # │                                                                           │
  # │ Docs: https://gatus.io/docs                                               │
  # └───────────────────────────────────────────────────────────────────────────┘
  status-page:
    image: oci.chezmoi.sh/localhost/alpine/gatus:stable
    cap_drop:
      - ALL
    networks:
      caddy-internal:
      default: # NOTE: Required for 3rd-party services to receive alerts
    read_only: true
    restart: unless-stopped
    user: gatus
    volumes:
      - gatus-perstistent:/var/lib/gatus

volumes:
  gatus-perstistent:
