---
# Copyright 2024
#
# Everyone is permitted to copy, distribute, modify, merge, sell, publish,
# sublicense or whatever the fuck they want with this software but at their
# OWN RISK.
# The author has absolutely no fucking clue what the code in this project
# does. It might just fucking work or not, there is no third option.
#
# IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.
# ---
version: "3.8"

services:
  develop:
    build:
      context: .
      dockerfile: Dockerfile
      platforms: [linux/amd64]
    ports: [3000:3000]
    restart: unless-stopped
    tmpfs:
      - /app/config/logs
    volumes:
      - ./config/bookmarks.yaml:/app/config/bookmarks.yaml:ro
      - ./config/custom.css:/app/config/custom.css:ro
      - ./config/services.yaml:/app/config/services.yaml:ro
      - ./config/settings.yaml:/app/config/settings.yaml:ro
      - ./config/widgets.yaml:/app/config/widgets.yaml:ro
      - ./config/assets/layered-waves-haikei.svg:/app/public/layered-waves-haikei.svg:ro
      - ./config/assets/icons/:/app/public/icons:ro
    deploy:
      resources:
        limits:
          memory: 400M
