# Copyright 2024
#
# Everyone is permitted to copy, distribute, modify, merge, sell, publish,
# sublicense or whatever the fuck they want with this software but at their
# OWN RISK.
# The author has absolutely no fucking clue what the code in this project
# does. It might just fucking work or not, there is no third option.
#
# IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.
---
name: Validate Commit (Compliance)

on:
  merge_group: {}
  pull_request: {}

permissions: {}

jobs:
  commitlint:
    name: Check the commits message format
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0

      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          cache: npm
      - name: Install all dependencies
        run: npm ci

      - name: Validate all PR commits
        if: ${{ github.event_name == 'pull_request' }}
        run: npx commitlint --from "${FROM}" --to "${TO}"
        env:
          FROM: ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }}
          TO: ${{ github.event.pull_request.head.sha }}

      - name: Validate all merge commits
        if: ${{ github.event_name == 'merge_group' }}
        run: npx commitlint --from "${FROM}"
        env:
          FROM: ${{ github.event.head_sha }}
