# Copyright 2024
#
# Everyone is permitted to copy, distribute, modify, merge, sell, publish,
# sublicense or whatever the fuck they want with this software but at their
# OWN RISK.
# The author has absolutely no fucking clue what the code in this project
# does. It might just fucking work or not, there is no third option.
#
# IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.
---
name: 💚 Validate Commit Compliancy

on:
  merge_group: {}
  pull_request: {}

permissions: {}

jobs:
  commitlint:
    name: ✅ Validate commits message format
    runs-on: ubuntu-22.04
    steps:
      - name: ⬇️ Checkout repository
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
        with:
          fetch-depth: 0

      - name: 🚧 Prepare NodeJS environment
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          cache: npm
      - name: 🚧 Install all dependencies
        run: npm ci

      - name: ✅ Validate all PR commits
        if: github.event_name == 'pull_request'
        run: |
          npx commitlint \
            --from "${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }}" \
            --to "${{ github.event.pull_request.head.sha }}" \
            --verbose

      # NOTE: This is a workaround to make commitlint required on PRs but optional on merge groups
      - name: 🙈 Allow merge group to pass
        if: github.event_name == 'merge_group'
        run: exit 0
